version: '3'

services:
  web:
    build: .
    ports:
      - "80:8000"
    restart: always
    env_file: ./server/.env.production
    command: npm start
    environment:
      NODE_ENV: production
      PORT: 8000
