version: '3'

services:
  event-manager:
    build: .
    ports:
      - "5555:5555"
    links:
      - mongodb
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
